"""Move telegram_chat_id from alerts to tenants

Revision ID: 6bafc1f16c9c
Revises: c8001d1843dc
Create Date: 2026-06-21 21:19:42.730258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bafc1f16c9c'
down_revision: Union[str, Sequence[str], None] = 'c8001d1843dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_rules', 'telegram_chat_id')
    op.drop_index(op.f('events_timestamp_idx'), table_name='events')
    op.add_column('tenants', sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'telegram_chat_id')
    op.create_index(op.f('events_timestamp_idx'), 'events', [sa.literal_column('timestamp DESC')], unique=False)
    op.add_column('alert_rules', sa.Column('telegram_chat_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
